# First, add the API
apiVersion: apps/v1
# This will be the deployment setup
kind: Deployment
metadata:
  # Name your Deployment here
  name: playground-backend
  labels:
    # label your deployment
    app: playground-backend
spec:
  # The number of pods/replicas to run
  replicas: 1            
  selector:
    matchLabels:
    # selector to match the pod
      app: playground-backend
  template:
    metadata:
      labels:
      # label your pod
        app: playground-backend
    spec:
      containers:
      # Add the container name for Kubernetes
      - name: backend
      # Add the local image name
        image: playground/backend 
        # never pull the image policy
        imagePullPolicy: Never
        ports:
        # port for running the container
        - containerPort: 3000
---
# First, add the Service API
apiVersion: v1
# This will be the Service setup
kind: Service
metadata:
  # Your service name
  name: playground-backend
spec:
  selector:
    # selector that matches the pod
    app: playground-backend
  # type of service
  type: LoadBalancer   
  ports:
  - protocol: TCP 
    # port for exposing the service        
    port: 3000
    # port for exposing the pod             
    targetPort: 5000